# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/Админ/Desktop/Post/ui/Done.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Done(object):
    def setupUi(self, Done):
        Done.setObjectName("Done")
        Done.resize(561, 756)
        self.CityLine = QtWidgets.QLineEdit(Done)
        self.CityLine.setGeometry(QtCore.QRect(10, 60, 541, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.CityLine.setFont(font)
        self.CityLine.setObjectName("CityLine")
        self.label = QtWidgets.QLabel(Done)
        self.label.setGeometry(QtCore.QRect(10, 20, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Done)
        self.label_2.setGeometry(QtCore.QRect(10, 100, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.NameLine = QtWidgets.QLineEdit(Done)
        self.NameLine.setGeometry(QtCore.QRect(10, 140, 541, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.NameLine.setFont(font)
        self.NameLine.setObjectName("NameLine")
        self.ImageLine = QtWidgets.QLineEdit(Done)
        self.ImageLine.setGeometry(QtCore.QRect(10, 390, 541, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ImageLine.setFont(font)
        self.ImageLine.setObjectName("ImageLine")
        self.label_3 = QtWidgets.QLabel(Done)
        self.label_3.setGeometry(QtCore.QRect(10, 350, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Done)
        self.label_4.setGeometry(QtCore.QRect(10, 440, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.FullTextBrowser = QtWidgets.QTextBrowser(Done)
        self.FullTextBrowser.setGeometry(QtCore.QRect(10, 480, 541, 192))
        self.FullTextBrowser.setObjectName("FullTextBrowser")
        self.DescBrowser = QtWidgets.QTextBrowser(Done)
        self.DescBrowser.setGeometry(QtCore.QRect(10, 220, 541, 121))
        self.DescBrowser.setObjectName("DescBrowser")
        self.label_5 = QtWidgets.QLabel(Done)
        self.label_5.setGeometry(QtCore.QRect(10, 180, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.pushButton = QtWidgets.QPushButton(Done)
        self.pushButton.setGeometry(QtCore.QRect(390, 690, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.label_status = QtWidgets.QLabel(Done)
        self.label_status.setGeometry(QtCore.QRect(20, 690, 351, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_status.setFont(font)
        self.label_status.setStyleSheet("color: green")
        self.label_status.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_status.setObjectName("label_status")

        self.retranslateUi(Done)
        QtCore.QMetaObject.connectSlotsByName(Done)

    def retranslateUi(self, Done):
        _translate = QtCore.QCoreApplication.translate
        Done.setWindowTitle(_translate("Done", "Form"))
        self.label.setText(_translate("Done", "City"))
        self.label_2.setText(_translate("Done", "Name"))
        self.label_3.setText(_translate("Done", "Image URL"))
        self.label_4.setText(_translate("Done", "Full Text"))
        self.label_5.setText(_translate("Done", "Descroption"))
        self.pushButton.setText(_translate("Done", "Добавить"))
        self.label_status.setText(_translate("Done", "Успешно"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Done = QtWidgets.QWidget()
    ui = Ui_Done()
    ui.setupUi(Done)
    Done.show()
    sys.exit(app.exec_())
